### ISSUE TITLE
Not working with Lano visualizer

### ISSUE THREAD

**Issue by 333andy** [tjhrulz/WebNowPlaying-BrowserExtension#10]
I am trying to play from Soundcloud, but it does not work with other sites as well.  My Lano visualizer works with foobar2000 when I tested it.  I have restarted Chrome and, since then, my PC.  In the general.ini menu on my visualizer there is no option for web media players, so do I have to do something for it to show up?  Help would be appreciated, thanks!

**Comment by tjhrulz** [comment]
The latest release of lano visualizer does not support webnowplaying. The GitHub repo for Lano has support added if you do a manual install from there.

**Comment by 333andy** [comment]
Thanks.  How can I do a manual install?

**Comment by tjhrulz** [comment]
Sorry I should have linked it before but was on mobile and feeling lazy :P 
https://github.com/marcopixel/Lano-Visualizer/#manual-installation

Edit: Dont move the WebNowPlaying.dll from that repo as it is outdated now, instead use the one the rmskin installs from https://github.com/tjhrulz/WebNowPlaying/releases/latest

**Comment by 333andy** [comment]
Thanks, the visualizer is working now but is there a way to get the song information to show up?
