### ISSUE TITLE
Options not visible

### ISSUE THREAD

**Issue by Roel69** [tjhrulz/WebNowPlaying-BrowserExtension#12]
After installing WebNowPlaying-BrowserExtension in Firefox, I coudn't see the Options page. The page is called **O**ptions.html, whereas in manifest.json it is **o**ptions.html.
I could make the options visible by changing options.html to Options.html in extensions.json in my Firefox profile.

Roel

**Comment by tjhrulz** [comment]
Interesting, it would seem that older version of Firefox were not case sensitive when it came to the options page but now are. (I wonder if this is also why the icon is currently broken for me in Firefox as well)

Thanks for the catch, I will fix this here in a few minutes and will try to push out an update over the next few days.
