### ISSUE TITLE
not working with Firefox Quantum 57.0.2 (64-bit) or is it just me

### ISSUE THREAD

**Issue by pin-dev** [tjhrulz/WebNowPlaying-BrowserExtension#13]
I usually used chrome and it's working perfectly with webnowplaying plugin but when i used the Firefox Quantum 57.0.2 (64-bit) it's not working with my skin, so i tried using the example skin even so it's not working so is it just me?

**Comment by tjhrulz** [comment]
Last I checked it was working fine, but try #7 because during your upgrade to Quantum Firefox might have reset it.
