### ISSUE TITLE
How to set network.websocket.allowInsecureFromHTTPS to true

### ISSUE THREAD

**Issue by vonsogt** [tjhrulz/WebNowPlaying-BrowserExtension#15]
The extension not working as well

**Comment by tjhrulz** [comment]
What about it is not working? Did you check network.websocket.allowInsecureFromHTTPS to make sure it is still set to true (Commonly forgotten to redo for the other install when you have the two installs of Firefox)?

**Comment by vonsogt** [comment]
how to make "network.websocket.allowInsecureFromHTTPS" true?

**Comment by tjhrulz** [comment]
Type about:config in the URL bar and search for that then set to true. See: https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/wiki/Troubleshooting#firefox

**Comment by vonsogt** [comment]
It's work! Thank you bro!
