### ISSUE TITLE
Support for YouTube Music

### ISSUE THREAD

**Issue by Hexality** [tjhrulz/WebNowPlaying-BrowserExtension#20]

**Comment by Hexality** [comment]
any support planned for YouTube Music?

**Comment by tjhrulz** [comment]
Already in the works just have not had time to finish it :P

**Comment by greeninja13** [comment]
Any word on how this is coming? I could help after I finish my classes in 5 days.

**Comment by qvalentin** [comment]
I added support for YoutubeMusic. Check out my fork: https://github.com/fihouttawater/WebNowPlaying-BrowserExtension

**Comment by tjhrulz** [comment]
You should have sent a pull request and I would have merged it in :P, although I actually already had everything you have implemented in your fork (Still need to get repeat all to work in a language agnostic way though).

Regardless it should be committed here shortly and pushed to the masses.

**Comment by qvalentin** [comment]
Glad to see you are still active here. Im no expert with GitHub, so I just forked it.
If there are other websites that need work, hit me up, I like to help.

**Comment by tjhrulz** [comment]
Yeah I am still active (And no github app properly sends me notifications), just busy. Honestly if you see another website stop working feel free message me on a platform like discord where I am much more likely to see it.

Also the support I just pushed to live!
