### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by AlexzanDev** [tjhrulz/WebNowPlaying-BrowserExtension#21]
Hello, I have an issue that seems nobody had before. Disclaimer: I use Firefox Nightly, always last version, tried with Chrome but no results.

On Firefox, the icon extension is a green puzzle piece, and when I put the cursor on it, it says: "**Not connected to Rainmeter. Click to troubleshoot.**" But clicks don't work. I even noticed that in Rainmeter logs, every 0.3 seconds the program throws this error: "_ImageName: Unable to open: C:\Users\Alessandro\Documents\Rainmeter\Skins\Monstercat-Visualizer\Song Information\Cover\0.png (Monstercat-Visualizer\Song Information\Cover\Cover.ini)_" I don't know if it's related to the plugin itself. Rainmeter is enabled in Windows Firewall, for public and private network. MV is already on WebNowPlaying. I have, of course, changed the _network.websocket.allowInsecureFromHTTPS_ to true in about:config. Any tips? Or I'm missing something? As for the websites, I've tried YouTube and SoundCloud, but it seems an extension problem.

**Comment by tjhrulz** [comment]
According to that the plugin is not pointing to the image to read. Given that I would double check that the plugin is installed and your computer because given that the plugin is likely not running.

Try reinstalling MV, but yeah the issue is not something wrong with the extension.

**Comment by AlexzanDev** [comment]
> 
> 
> According to that the plugin is not pointing to the image to read. Given that I would double check that the plugin is installed and your computer because given that the plugin is likely not running.
> 
> Try reinstalling MV, but yeah the issue is not something wrong with the extension.

Hey, just wanted to let you know that reinstalling the WebNowPlaying plugin did the trick. Thanks for your help!
