### ISSUE TITLE
Webplayer request: Stingray Music

### ISSUE THREAD

**Issue by zudzug** [tjhrulz/WebNowPlaying-BrowserExtension#23]
Greetings,

I find your code fascinating. I would love to find support for Stingray Music Webplayer. It's big in Canada. I wouldn't know about the rest of the world. There are literally thousands of radio channels on there.

Here's a quick link to the web player. You can sign up for a free account with an email address and get a 7 days trial. 
https://webplayer.stingray.com/ 

The way the website works is fairly similar to that of the old youtube. It would require pulling elements by class from a dynamic webpage. This I can figure out, but the rest of your code still throws me off base for the moment.

Regards,

**Comment by tjhrulz** [comment]
Ill add it to my list of things to do when I find time. :P

**Comment by keifufu** [comment]
Please open a new Issue on [this](https://github.com/keifufu/WebNowPlaying-Redux) repository if you are still interested.
