### ISSUE TITLE
Permanently fetching

### ISSUE THREAD

**Issue by charlesthememe** [tjhrulz/WebNowPlaying-BrowserExtension#24]
Tried with both Firefox and Chrome (Firefox has the websocket change in the config page as well), just says Fetching... for both top and bottom text for both browsers on youtube and soundcloud.

**Comment by charmarkk** [comment]
+1

**Comment by charmarkk** [comment]
Strike that - working for me now. I had to update to version 0.4 of the rmskin from the releases here (https://github.com/tjhrulz/WebNowPlaying/releases/). @charlesthememe maybe that'll help.

Github is so hard to navigate.

**Comment by tjhrulz** [comment]
Where does it say fetching?

**Comment by charlesthememe** [comment]
I've resolved this issue by updating the rmskin for the original media
player iirc. No longer a problem and just user error by the looks of it

**Comment by tjhrulz** [comment]
Cool, my apologies I could not come to your aid sooner :P
