### ISSUE TITLE
Spotify high res album art

### ISSUE THREAD

**Issue by tjhrulz** [tjhrulz/WebNowPlaying-BrowserExtension#26]
So spotify has slightly changed how they do their album art, now instead of it sometimes being low res it is now always low res.

My general rule of thumb when it comes to album art is do the best you can get, and the issue is in this case the best I can get on the webpage is 64x64 which is pretty low res. Now with their API I can get higher but given how rate limited that is and with the userbase there is that will not scale well.

So if anyone knows of a good reliable way to do this feel free to lend a hand

**Comment by keifufu** [comment]
Fixed [here](https://github.com/keifufu/WebNowPlaying-Redux), development will continue over there and while it's a separate listing on the webstore for now it should eventually replace the existing listing.
