### ISSUE TITLE
Deezer support broken

### ISSUE THREAD

**Issue by err53** [tjhrulz/WebNowPlaying-BrowserExtension#27]
When playing from Deezer, no information is detected (album art is blank, title and artist is blank, no progress bar). Youtube support works fine, so it's not a connection issue. I'm using Deezer free, Brave with the Chrome Web store extension, and the Monstercat Visualizer FYI.

**Comment by tjhrulz** [comment]
I just pushed an update to fix that, sadly volume and progress control support is not going to work due to how backwards their redesign is under the hood.

Progress still updates just fine though, but volume will just always say 100

**Comment by SimplyNaOH** [comment]
Is this fix pushed to the firefox add-on store? If so, it stopped working again; otherwise, how can I install the patched version?

Thanks!

**Comment by aksasahara** [comment]
Having the same issue as SimplyNaOH

**Comment by AyrtonColl** [comment]
Have the same issue too. I'm using deezer on firefox and The monstercat visualizer.
