### ISSUE TITLE
Light Icon for Chrome Dark Mode

### ISSUE THREAD

**Issue by JeremyKerman** [tjhrulz/WebNowPlaying-BrowserExtension#29]
With the recent update to Chrome, dark mode has been enabled for the browser. It would be nice to have the ability to switch out the extension icon to a lighter version to help spot it, as at the moment black on grey can be a bit hard to see at times.

**Comment by tjhrulz** [comment]
I will have to look into how to define that so that I can do that. The icon is dark enough for me that I can see it just fine in dark mode, which is what I daily drive, but I guess not for everyone :P

**Comment by tjhrulz** [comment]
Well this is way more complex than it needs to be it would seem. I may wait for Google to add a more proper way to detect dark mode and just define it in the manifest instead of needing to constantly run another background script, either that or I may just add it as an option in the settings.

**Comment by keifufu** [comment]
Closing this to move discussion over to the new repository ([link](https://github.com/keifufu/WebNowPlaying-Redux/issues/1))
