### ISSUE TITLE
Error from Spotify Cover Art

### ISSUE THREAD

**Issue by SaberAkiyama** [tjhrulz/WebNowPlaying-BrowserExtension#33]
I've saw an error on Rainmeter log was "Web Side Error: Error updating cover for Spotify"
I use Spotify Web Player with WNP Extension v0.4.6 (Sep 18th 2019)

**Comment by ceylon23** [comment]
Confirmed error. I reported this issue in the plugin repository.

EDIT: This issue is not occurring with WebNowPlaying Spotify with spicetify-cli.

**Comment by SaberAkiyama** [comment]
> Confirmed error. I reported this issue in the plugin repository.
> 
> EDIT: This issue is not occurring with WebNowPlaying Spotify with spicetify-cli.

I never use Spicetify CLI. I use Spotify Web Player for Chrome.

**Comment by SaberAkiyama** [comment]
Update: Even "Play/Pause" button didn't work as well.

**Comment by ceylon23** [comment]
UPDATE: @tjhrulz has released a new version of the extension and this issue is now fixed. @SaberAkiyama could you please verify and close this issue?

**Comment by tjhrulz** [comment]
Thanks for the help keeping my issues clean @ceylon23, really wish my github app would start doing push notifications on issues correctly again so I actually see these things when they happen.

**Comment by SaberAkiyama** [comment]
Another error, same as previous issue
