### ISSUE TITLE
Getting Web Side Error:Error updating shuffle for Youtube

### ISSUE THREAD

**Issue by ConfusedOwlet** [tjhrulz/WebNowPlaying-BrowserExtension#34]
Getting this error while on YouTube using Firefox Quantum (69.0.1). Tried reinstalling the extension and relaunching Rainmeter, but no change. I turned on Debugging with Rainmeter, and got this whole error.

`Web Error:TypeError: document.getElementById(...).children[0].children[0].children[1] is undefined`

This error logs constantly. With a single song that's just paused, I get about 14 in a 10 (ten) second period. With a playing song, especially when the song is in a playlist, I got 20 in 1 (one) second.

**Comment by tjhrulz** [comment]
This should be fixed with the update I pushed out a few weeks back.
