### ISSUE TITLE
Couldn't get WebNowPlaying Extensions working on firefox in any ways

### ISSUE THREAD

**Issue by Mass1milian0** [tjhrulz/WebNowPlaying-BrowserExtension#36]
i have searched trough the web before opening an issue, neither my antivirus or my windows defender are blocking rainmeter in any ways, rainmeter version is updated to the latest (4.3.1.3321 64-bit)
firefox flag network.websocket.allowInsecureFromHTTPS is set to true, and the webnowplaying plugin is installed in rainmeter, i get this message from the extensions 
![immagine](https://user-images.githubusercontent.com/20503622/67128976-33367800-f1f5-11e9-9a87-31f8386156ec.png)
no skin supporting webnowplaying works, not even the example skin you get when installing the webnowplaying plugin

**Comment by tjhrulz** [comment]
Double checking, did you allow it through your firewall as shown in the Wiki? https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/wiki/Troubleshooting

**Comment by gemma350mb** [comment]
I'm having the same problem, I simply can't get it working. I don't have any messages from the extension though.

**Comment by Dexy2811** [comment]
same issue is still present

**Comment by Gamerbiomek2** [comment]
same issue but now with Google Chrome too

**Comment by katattacktime** [comment]
Having this problem right now as well. Was working and then now isn't. May be connected to a Windows update? That's the only thing that's recently changed on my system. Works perfectly fine in Chrome but not Firefox even after troubleshooting via the Wiki.

**Comment by Mass1milian0** [comment]
> 
> 
> Double checking, did you allow it through your firewall as shown in the Wiki? https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/wiki/Troubleshooting

yes i did, re-checked just in case, after this commit the plugin suddenly started working, but it seems that something broke again, and the issue persists once again


EDIT: it is working again today date: 21/09/2020 european format
