### ISSUE TITLE
Tidal doesn't work

### ISSUE THREAD

**Issue by aarch-angel** [tjhrulz/WebNowPlaying-BrowserExtension#37]
The extension doesn't work on tidal for me - it works on other sites like youtube and soundcloud, but for whatever reason nothing shows up when playing from tidal.

**Comment by aarch-angel** [comment]
Seeing [issue 25]( https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/25 ), I'd assume Tidal probably obfuscated something again - I'm not experienced enough in this sort of stuff to figure it out though, otherwise I'd try and help and make a PR :(

**Comment by tjhrulz** [comment]
Its all good, I will get it fixed sometime this week. (I really wish github would add notifications to their desktop app)

**Comment by adammparsons** [comment]
Tidal isn't currently working for me either, not sure if they've changed something again or if I'm just having issues, but every other music service has worked fine with the plugin.

**Comment by salem-macewan** [comment]
yep. same issue.

**Comment by tjhrulz** [comment]
Fixed https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/15bc7dd50cd819fe1b0d7bdad7677ec7dc226dc2
