### ISSUE TITLE
Youtube Music Cover Art is broken

### ISSUE THREAD

**Issue by zusorio** [tjhrulz/WebNowPlaying-BrowserExtension#38]
Covers just aren't working for youtube music. They're working fine for other services. I looked into the code and found that the element for getting the cover seems to have changed. It's class is now `image style-scope ytmusic-player-bar`. There seem to have been other changes as well and I couldn't figure out how to efficiently debug this so I gave up on trying to fix this myself. If you have any questions I'm happy to help

**Comment by zusorio** [comment]
Fixed in #40 please merge

**Comment by tjhrulz** [comment]
(For future reference if you put in the commit notes for https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/83670abd5a1142901677a493a3eae169f4f56465 fixes #40 it will auto close an issue when I merge it)

**Comment by tjhrulz** [comment]
Also thank you for your help catching bugs! My apologies it did not get merged sooner
