### ISSUE TITLE
Google Play Music change STATE to 0 when not playing

### ISSUE THREAD

**Issue by Devo7v** [tjhrulz/WebNowPlaying-BrowserExtension#43]
Firefox: v73.0.1
WebNowPlaying: v0.4.7
Site: Google Play Music (https://play.google.com/music/listen)

I have a skin that queries the STATE of the WebNowPlaying extension.  When Google Play Music is not loaded, STATE=0.  When I open Google Play Music but do not play anything, STATE=0.  When I play and pause music STATE=1 or 2 respectively.  When the music finishes playing or I clear my current playlist (meaning the play button on the website becomes greyed out), STATE=2.

I believe that when no music is playing (meaning music has finished playing or the playlist is empty), STATE should always =0.

**Comment by tjhrulz** [comment]
Google play music support is dropped since google has dropped it, YouTube music is fully functional now
