### ISSUE TITLE
Spotify Web Player doesn't working

### ISSUE THREAD

**Issue by SaberAkiyama** [tjhrulz/WebNowPlaying-BrowserExtension#44]
When I play Spotify Web Player with extension, it doesn't appear on Song, Artist, Playback state, Progress bar, etc.

WNP Extension Version: v0.4.7
Browser: Google Chrome v80.0.3987.132 (Official Build)

**Comment by TheNoFace** [comment]
Spotify has changed its HTML class names. If you want spotify to work, you have to edit [spotify.js](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/blob/master/Websites/Spotify.js).

**Comment by Skyyblaze** [comment]
> 
> 
> Spotify has changed its HTML class names. If you want spotify to work, you have to edit [spotify.js](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/blob/master/Websites/Spotify.js).

What exactly would I need to change and how would I go about it in Firefox and Edge Chromium? I have the same issue.

**Comment by iancbogue** [comment]
Still having this issue. I tried using the spotify.js that you linked @TheNoFace, which is slightly different than the one that is in the extension on my PC. Unfortunately, Edge Chromium won't let me use it because it considers the extension corrupt after I change spotify.js.
