### ISSUE TITLE
WebnowPlaying Companion Not Working With Google Music (dedicated site) -Album Art Missing

### ISSUE THREAD

**Issue by JordansplaceYT** [tjhrulz/WebNowPlaying-BrowserExtension#53]
This is in relation to rainmeter. it is managing to grab everything but album art. 
![Screenshot_1](https://user-images.githubusercontent.com/65009223/92329169-8ad41100-f05d-11ea-95f8-103aa400dd78.png)

https://music.youtube.com/ - site with issues

**Comment by tjhrulz** [comment]
Google Music support has been dropped since google has dropped the site, youtube music currently works
