### ISSUE TITLE
WebNowPlaying Extension not connected to Rainmeter in Chrome

### ISSUE THREAD

**Issue by Gamerbiomek2** [tjhrulz/WebNowPlaying-BrowserExtension#54]
FireFox version seems to work, but Chrome version now says "not connected to Rainmeter". 
![WebNowPalying Extension not connected to Rainmeter](https://user-images.githubusercontent.com/22333494/92685725-58007600-f306-11ea-8217-dae1619695fa.png)

I have Rainmeter allowed through my firewall. 
![Rainmeter Allowed through firewall](https://user-images.githubusercontent.com/22333494/92686267-54212380-f307-11ea-9796-b478a7c73ee7.jpg)

**Comment by sirbottoms98** [comment]
I also have this issue

**Comment by Jin-hjs** [comment]
Also having this issue after reboot

**Comment by sirbottoms98** [comment]
For me I had to turn off my adblock. I then whitelisted the sites I use for music like YouTube, YouTube Music, Spotify, Soundcloud, etc.... in order to get it to work properly. Would be nice for a more direct solution. I heard adding the extension to adblocks web socket filter makes it work but idk how to do that. I'm using chrome btw

**Comment by Gamerbiomek2** [comment]
Seems like Adblock Plus blocks the extension for some reason.
I will leave this open until @tjhrulz  or someone else can fix it.

**Comment by sirbottoms98** [comment]
The normal Adblock also blocks the extension as well. Really unfortunate

**Comment by TF390** [comment]
I'm having the same issue but in Firefox. Turning off Adblock in Firefox hasn't resolved my issue so far.

**Comment by sirbottoms98** [comment]
With firefox you have to do change "network.websocket.allowInsecureFromHTTPS" in the about:config page in Firefox to true.

I don't use Firefox so I don't know how well this works

**Comment by Gamerbiomek2** [comment]
Just found out that uBlock Origin also blocks the extension but not the regular Adblock, hmm?

**Comment by sirbottoms98** [comment]
For me regular Adblock blocks the extension

**Comment by Gamerbiomek2** [comment]
> For me regular Adblock blocks the extension

not for me

**Comment by tjhrulz** [comment]
@Gamerbiomek2 I'll be back from vacation next week and I will look into this

**Comment by tjhrulz** [comment]
So I run uBlock origin normally with chrome and have no issues with this. Are you guys running beta versions of chrome by chance or have extra rules/filter sets?

**Comment by bxff** [comment]
I have the same issue but on Firefox, just like @TF390, I also have many extensions such as HTTPS Encryption, uBlock Origin but nothing worked.

**Comment by BlackcatCXII** [comment]
i have the same issue on brave  here's a list of what my add blocker is blocking if it help
[New Text Document.txt](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/files/5680939/New.Text.Document.txt)

**Comment by jcs021102** [comment]
I am also getting a similar issue, on brave. The browser is identical to chrome as far as im aware with the exception of a built in adblocker, but nothing seems to be listed about the extension, This issue popped up quite recently too as before everything was working fine.

**Comment by mich4s74** [comment]
Yes brave´s built-in adblock , blocks the tracking of the plugin.

**Comment by oarasaiah** [comment]
Perhaps whitelisting the extension on ublock would allow this to work, but I'm not sure on how to do that.

**Comment by RT-Tap** [comment]
Has anyone figured this out?  I'm using Brave and just found this project, reluctant to open a new issue so was wondering if theres something I need to change in order to get it  to work?
I put the dll in Vault>>Plugins then downloaded the extension and example skin however can't get it up and running. 
@tjhrulz <-- because you told me to somewhere in the readme or extension info

**Comment by turannul** [comment]
Same issue  Edge / Windows 11

**Comment by keifufu** [comment]
If people still run into this issue, please move discussion to [this](https://github.com/keifufu/WebNowPlaying-Redux) repository.
