### ISSUE TITLE
Error updating cover for Youtube Music

### ISSUE THREAD

**Issue by AbleOne** [tjhrulz/WebNowPlaying-BrowserExtension#59]
![image](https://user-images.githubusercontent.com/11058655/95070911-827cfd80-0711-11eb-9fa5-c1eff22a91cb.png)

**Comment by AbleOne** [comment]
@tjhrulz, wow, after pulling master I've discovered that this has been fixed already...
It is fixed here in this repo, but in the [Chrome Web Store ↗](https://chrome.google.com/webstore/detail/webnowplaying-companion/jfakgfcdgpghbbefmdfjkbdlibjgnbli) there is version with not correct code for getting YTMusic cover:

this [line 68](https://github.com/AbleOne/WebNowPlaying-BrowserExtension/blob/4d311d3c0244e35dc4e596dcfe449e9f6745b7d0/Websites/YoutubeMusic.js#L68) still has   
`var videoID = document.getElementsByClassName("ytp-title")[0].children[1].children[0].href;`  
instead of  
`var videoID = document.getElementsByClassName("ytp-title")[0].children[0].children[0].href;`

I wanted to make PR with that fix, but if fix already exists, we only need to wait when it will be uploaded to Chrome Web Store with new version (hopefully) 👌👍👍😉

**Comment by tjhrulz** [comment]
Hmmm odd I thought that My last round of fixes I made I pushed out to live, guess I must not have. I plan on this week, probably tomorrow, going through and readressing compatibility with all platforms once I'm done with that I will make sure that the chrome Web store and Firefox store are both version matching the current github repo

**Comment by AbleOne** [comment]
@tjhrulz, great, mate!! 💪🤟🎉🎉  
Yayyyyy!!  Looking forward for this!

**Comment by tjhrulz** [comment]
Just figured I would update you I have pretty much everything done at this point just got to work a little more on tidal support and brush up a few bugs with Deezer and we will be good to go.

**Comment by tjhrulz** [comment]
Fixed as of https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/a7c90978388e9e7151fea473c78ee836d62887ef.

Pushing out to both webstores here, should seem them on your computer in a few hours
