### ISSUE TITLE
doesn't work with spotify

### ISSUE THREAD

**Issue by R3alHumanBe1ng** [tjhrulz/WebNowPlaying-BrowserExtension#60]
works with everything else but just not spotify for some reason

**Comment by BurntKrispe** [comment]
It appears that they removed the Spotify API here: [This was causing issues for some people due to network configurations so
I worked around it.](https://github.com/tjhrulz/WebNowPlaying)

**Comment by tjhrulz** [comment]
Spotify was never fully broken but is fully working as of https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/8e517b52b05f4d6a82f3c22d268ee54cad54b103
