### ISSUE TITLE
Webplayer request: Apple Music

### ISSUE THREAD

**Issue by ThatStella7922** [tjhrulz/WebNowPlaying-BrowserExtension#61]
i already tried using generic support
![image](https://user-images.githubusercontent.com/10524728/95790420-8e7e3780-0c9c-11eb-8780-5e6da95b9eeb.png)

but i just get this
![image](https://user-images.githubusercontent.com/10524728/95790431-950caf00-0c9c-11eb-9b81-0ccbe629ab94.png)

with no album art or proper song info reported even though the site is reporting info to chrome properly 
![image](https://user-images.githubusercontent.com/10524728/95790482-b1105080-0c9c-11eb-9e9d-e5b08fe8ab10.png)

**Comment by tjhrulz** [comment]
I don't have any apple products so I might not be able to easily add this but I will have to see.

However I did not know that Chrome added such a media playback info banner, I wonder if it is possible to scrape that to improve the generic support...

Regardless I will have to look into this

**Comment by tjhrulz** [comment]
Addressed in commit https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/commit/aee99801f59399c8258f87328f2b1a2c95fd2fc6
Full apple music support has been added, also Apple was the king of rating support back in the day so it was shocking to see they have no rating system at all on Apple Music 🤷

**Comment by ThatStella7922** [comment]
Many thanks! 

And as for 
> Apple was the king of rating support back in the day

The Music app on macOS and iTunes still have music rating built in even for Apple Music tracks (not just local ones) but it’s gone from the web version of Apple music
