### ISSUE TITLE
Amazon Music

### ISSUE THREAD

**Issue by jondiaz1985** [tjhrulz/WebNowPlaying-BrowserExtension#65]
I'm seeing an issue with this connecting to Amazon Music. It seemed to stop working last week. Still works with basically everything else I've tried. Any ideas?

**Comment by js126696** [comment]
I'm also seeing this issue.  Amazon updated their interface recently, so I'm guessing something changed on Amazon's end?

**Comment by jondiaz1985** [comment]
I was thinking the same thing. But, I'm still EXTREMELY new to this stuff so I'm not sure where to start looking really.

**Comment by jondiaz1985** [comment]
Found some new information that may help with where to look. In the past, my Windows notifications would only say Amazon Music was playing. Now it says all of the song/artist/album information, including the album art.

**Comment by tjhrulz** [comment]
Wow they completely overhauled it... Working on an update now

Maybe they finally fixed their shitty volume controls
