### ISSUE TITLE
Title and Description with Youtube when switching away from video

### ISSUE THREAD

**Issue by Cabola** [tjhrulz/WebNowPlaying-BrowserExtension#66]
This is a direct copy from my bug issue report to "[Monstercat-Visualizer](https://github.com/marcopixel/Monstercat-Visualizer/issues/330)" as I thought that rainmeter skin was the one that had the issue/bug. But they sent me here to report it instead so I'm copy pasting it instead..

### Describe the bug
If you use the Webplayer and watch a youtube video, then click away from the video to "Home" aka Youtube Index or the "Subscriptions" page. Basically a page where you find a list of videos to view. The title and description of the video you were watching before switching to the video list remains. The Title is displayed twice and the Description once, but further down than the position normally is.

### To Reproduce
Use webplayer and watch a YT video then click the YT logo to be taken to the index page.

### Screenshots
This is how it looks like when you're watching a YT video:
![normal](https://user-images.githubusercontent.com/19853946/99152223-b815ee80-26a0-11eb-8d97-76fe5d9087d5.png)
This is how it looks like after you switch to the index page of YT:
![bug](https://user-images.githubusercontent.com/19853946/99152222-b77d5800-26a0-11eb-8df8-e3a03de88aa3.png)

### System information
* **OS Version:** Windows 10 Pro 2009 64-bit (build 19042) - English (1033)
* **Spotify Version:** The SpotifyPlugin.dll is version 1.9.3.0
* **Firefox Plugin Version of WebNowPlaying:** 0.4.8

**Comment by Batgoonz** [comment]
Got the same problem. they just told me to submit the same bug here. Still no fixes

**Comment by tjhrulz** [comment]
Huh, I don't use the whole youtube nav thing, guys I will have to fix that today.
