### ISSUE TITLE
SoundCloud album art not pulling

### ISSUE THREAD

**Issue by TheBSGamer** [tjhrulz/WebNowPlaying-BrowserExtension#67]
SoundCloud album art is no longer working for me. I can play, pause, skip, seek, and get the visualizer, but the album art is no longer there. Tested YouTube and it pulls album art as does other supported sites. I did get an update to SoundCloud and it moved my now playing bar to the top, so maybe the renamed/remapped some elements or something?

Seems to be an issue with the extension as far as I can tell. If logs additional troubleshooting is needed, I can gladly provide or attempt if necessary.

**Comment by thehearthz** [comment]
same （；´д｀）

**Comment by tjhrulz** [comment]
This has already been fixed, I just need to wait for both appstores to let me deploy it
