### ISSUE TITLE
Chrome webstore link is down

### ISSUE THREAD

**Issue by Ben243** [tjhrulz/WebNowPlaying-BrowserExtension#69]
It appears that this is no longer searchable on the google chrome web store. Not sure what the reason was, but it was pretty recent as I had been installing new browsers within the past two weeks and only noticed it now

**Comment by tjhrulz** [comment]
You actually caught it within a few hours of it happening, I already reached out to the Chrome team on Tuesday and am still waiting for a response.

Basically Google seems to have decided to updated their bot looking for misleading/malicious extensions in the chrome webstore and it seems to have decided that my extension listing a small amount of some of the sites supported was against TOS and pulled it from the webstore.
