### ISSUE TITLE
Websocket insecure (Firefox only)

### ISSUE THREAD

**Issue by tjhrulz** [tjhrulz/WebNowPlaying-BrowserExtension#7]
Since Firefox checks that any websockets on a secure page are also secure any Firefox user would need to go to the about:config page in Firefox and set network.websocket.allowInsecureFromHTTPS to true.

I am sorry that you have to do this for the time being, but using a self signed SSL Certificate would likely throw more errors even though the connection is only over localhost.

**Comment by Ryonez** [comment]
Is there a way to use letsencrypt? Because I don't intend to gut security systems to make this work.

Is this because http is being used to send info to localhost?

**Comment by nodgear** [comment]
> Is there a way to use letsencrypt? Because I don't intend to gut security systems to make this work.
> 
> Is this because http is being used to send info to localhost?
letsencrypt for every user that installs? secure websocket connections works a bit differently.
it is just because the ws connection goes thru another address, and to be accepted on a secure website it should also be connecting to a secure socket (wss)

**Comment by keifufu** [comment]
Going to close this to clean this repo up, this discussion can continue [here](https://github.com/tjhrulz/WebNowPlaying/issues/25)
