### ISSUE TITLE
Apple Music not getting any information besides song progress

### ISSUE THREAD

**Issue by L-Ratio** [tjhrulz/WebNowPlaying-BrowserExtension#70]
It doesn't pull any information besides the song time/progress 
In fact it doesn't even detect apple music unless you check " Attempt to support unknown websites using the generic script "

**Comment by tjhrulz** [comment]
Apple Music support got held up from being in the extension stores due to an issue with chrome, in order to get it in the meantime you will have to sideload the extension. Support should be out soon though as I just finished fixing the issues with the Chrome Web Store team.
