### ISSUE TITLE
Soundcloud

### ISSUE THREAD

**Issue by KRK99** [tjhrulz/WebNowPlaying-BrowserExtension#71]
Sound Cloud thumbnail/cover is not showing . 
youtube is fine

**Comment by KRK99** [comment]
@tjhrulz

**Comment by huds0nx** [comment]
having same problem

**Comment by tjhrulz** [comment]
While I had a partial fix in place I have now fully fixed this by planning release a new version of the Rainmeter plugin, this should prevent further security issues from preventing downloading of album art in the future. https://github.com/tjhrulz/WebNowPlaying/commit/83cb240ca54c907186b61e93d076e8d1ab54a4ac

**Comment by trevor-pope** [comment]
Hate to reopen this, but I still don't get album art. 
Currently running on Firefox v. 88.0.1 64 bit. I have the most recent extension (version 0.5.0).

Rainmeter reports the following:

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)


Firefox also displays a warning when rainmeter is running :
"Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page."

[This](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_compatibility) might be useful information regarding background/persistent pages.

**Comment by tjhrulz** [comment]
> Hate to reopen this, but I still don't get album art.
> Currently running on Firefox v. 88.0.1 64 bit. I have the most recent extension (version 0.5.0).
> 
> Rainmeter reports the following:
> 
> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
> at System.Net.HttpWebRequest.GetResponse()
> at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)
> 
> Firefox also displays a warning when rainmeter is running :
> "Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page."
> 
> [This](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_compatibility) might be useful information regarding background/persistent pages.

Update your Rainmeter plugin to the one that fixes soundcloud's limited SSL/TLS compatibility and that should fix it. https://github.com/tjhrulz/WebNowPlaying/releases

As for the Firefox background page I am guess they just dropped support for the way I check that the plugin is up to date, I kind of quickly implemented it the first time so it may be I just need to update that to a better method

**Comment by trevor-pope** [comment]
Works like a charm, and no more firefox warning as well!
