### ISSUE TITLE
No Album Art Apple Music 

### ISSUE THREAD

**Issue by L-Ratio** [tjhrulz/WebNowPlaying-BrowserExtension#72]
On apple music it is not getting the album art 
The lightblue highlight is the image and the light gray highlight is what is being referred to in applemusic.js

![image](https://user-images.githubusercontent.com/54047268/113618252-a2d03b00-9614-11eb-9123-811c2aeb1dbe.png)

**Comment by L-Ratio** [comment]
The error being generated by rainmeter is 
`System.UriFormatException: Invalid URI: The format of the URI could not be determined.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

   at System.Net.WebRequest.Create(String requestUriString)

   at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)`
   
   
   The following code is where the album art shows up at 
   
   `<div class="media-artwork-v2 media-artwork-v2--aspect-ratio media-artwork-v2--downloaded media-artwork-v2--no-border media-artwork-v2--chrome-playback web-chrome-playback-lcd__artwork-container" style="--background-color:#ebebeb; --aspect-ratio:1" id="ember11" data-aspect-ratio="1">

            <picture>
                 
                     <source srcset="https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/27/a0/fa/27a0fa9e-a975-3b3e-503f-e42c16427fde/190295384227.jpg/44x44bb-60.jpg 44w, https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/27/a0/fa/27a0fa9e-a975-3b3e-503f-e42c16427fde/190295384227.jpg/88x88bb-60.jpg 88w" type="image/jpeg">

              <img class="media-artwork-v2__image" sizes="null 44px" src="/assets/artwork/1x1.gif" decoding="async" height="44" width="44" alt="I Don't Care" role="presentation">
            </picture>


</div>`

**Comment by tjhrulz** [comment]
I believe this was already fixed in the repo but I had not pushed out the code. Regardless it should be good now once the new extension gets pushed out and you download the new version of the plugin that includes https://github.com/tjhrulz/WebNowPlaying/commit/83cb240ca54c907186b61e93d076e8d1ab54a4ac

**Comment by L-Ratio** [comment]
I have downloaded the new plugin version and side loaded the new extension version but same thing is happening if needed I can provide more of the apple music album art code
1st error that appeared 
```
ERRO (20:35:21.029) : Unable to get album art from: .jpg/2000x2000.jpg
DBUG (20:35:21.032) : System.UriFormatException: Invalid URI: The format of the URI could not be determined.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

   at System.Net.WebRequest.Create(String requestUriString)

   at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)

```
2nd error that appears everytime a new song plays
```
ERRO (20:39:10.109) : WebNowPlaing.dll - Error converting duration into integer
DBUG (20:39:10.110) : System.FormatException: Input string was not in a correct format.

   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   at System.Int16.Parse(String s, NumberStyles style, NumberFormatInfo info)

   at WebNowPlaying.Measure.WebNowPlaying.OnMessage(MessageEventArgs arg)
```

**Comment by tjhrulz** [comment]
Unfortunately I don't have access to Apple music at the moment, the image issue looks like my code to get the high-rise album art is n't working right and I probably can fix without access.

The duration issue though might be a little harder.

**Comment by L-Ratio** [comment]
If needed I can try to provide more apple music code for you I just don't know what I need to look for

**Comment by tjhrulz** [comment]
Add me on Discord and we can do some screen sharing so I can see the updated code and try some things.

My discord is tjhrulz#5476

**Comment by HawksAreNeat** [comment]
I sent you a fr my username is Hawk#4872

**Comment by L-Ratio** [comment]
> 
> 
> Add me on Discord and we can do some screen sharing so I can see the updated code and try some things.
> 
> My discord is tjhrulz#5476

I sent you a fr my username is Hawk#4872

**Comment by keifufu** [comment]
Fixed in [this](https://github.com/keifufu/WebNowPlaying-Redux) repository. Future development of this extension will continue there too.
