### ISSUE TITLE
Update Spotify support for May 2021 refresh

### ISSUE THREAD

**Issue by tjhrulz** [tjhrulz/WebNowPlaying-BrowserExtension#74]
Just preemptively opening up this issue because of course 4 hours after I push a patch to fix the current version I hear they are releasing a new design that is a server side rollout.

Once I have the new version I will update support, as for how long that will take 🤷 
If anyone gets it before me wants to tweak for the new version be my guest, I hope that based on the design docs that they are now always showing the HQ album art

**Comment by mertturunc** [comment]
@tjhrulz  The information about my app versions and log files:

- Opera Version:76.0.4017.107
- Windows 10 Home Single Language 2009 64-bit (build 19042) - Turkish (1055) (as you mentioned before it's a different language)
- Rainmeter 4.4.0.3447 beta (64-bit)
- WebNowPlaying 0.5.0.0
- WebNowPlaying Companion 0.5.0

As far as I know from the tests Opera's ad blocker and uBlock Origin doing nothing to extension.

gist [link](https://gist.github.com/mertturunc/ddb23f7e7d33ebb25285ea085d0a8ece) for logs and nowplaying bar 

Screenshot from open.spotify.com:
![image](https://user-images.githubusercontent.com/16109023/118440039-be3c6480-b6ef-11eb-8c93-aa872b9007fb.png)

**Comment by tjhrulz** [comment]
> @tjhrulz  The information about my app versions and log files:
> 
> - Opera Version:76.0.4017.107
> - Windows 10 Home Single Language 2009 64-bit (build 19042) - Turkish (1055) (as you mentioned before it's a different language)
> - Rainmeter 4.4.0.3447 beta (64-bit)
> - WebNowPlaying 0.5.0.0
> - WebNowPlaying Companion 0.5.0
> 
> As far as I know from the tests Opera's ad blocker and uBlock Origin doing nothing to extension.
> 
> gist [link](https://gist.github.com/mertturunc/ddb23f7e7d33ebb25285ea085d0a8ece) for logs and nowplaying bar 
> 
> Screenshot from open.spotify.com:
> ![image](https://user-images.githubusercontent.com/16109023/118440039-be3c6480-b6ef-11eb-8c93-aa872b9007fb.png)
> 

Please open a new issue, do not post this in an unrelated issue

**Comment by NeroYuki** [comment]
@tjhrulz Sorry for necro this issue but i came from tjhrulz/WebNowPlaying#66. Currently the extension can fetch track infomation (except album name - screenshot from the example skin) 
![image](https://user-images.githubusercontent.com/24820831/136679724-de09c745-b3bb-4576-8976-9f6f359d4c6b.png)
But almost none of the control is working. Except the previous command which instead pause/play the track for whatever reason
My rainmeter log is also flooded with similar Web Side Error but only for state, repeat and volume, error and debug message below
![image](https://user-images.githubusercontent.com/24820831/136679842-5680a7f2-f810-4bc6-9151-b2e0b6a077b7.png)
My system information is as follow:

- Windows 10 64-bit version 21H1
- Spotify Web Player on Microsoft Edge 94.0.992.38 (Official build) (64-bit)
- WebNowPlaying Companion on 0.5.0 (Connected and sending info, have access to the site)
- WebNowPlaying on 0.5.0.0

**Comment by Novadestin** [comment]
I just discovered this issue myself when trying to help someone, so it is still an ongoing problem. But, whatever happens, thank you for all your help and hard work tjhrulz!

**Comment by Gabanders** [comment]
I also would like to up this issue as I am also having the same problem with the previous posters. Hoping for a fix soon.

**Comment by volktwins** [comment]
I also have same issue

**Comment by nodgear** [comment]
Just checked, ws connection fails for spotify: https://i.wisp.run/f/6b9bmV.png
the connection seems to not even open, as this error also shows up on my electron app: https://i.wisp.run/f/1uy2sb.png

**Comment by keifufu** [comment]
Fixed [here](https://github.com/keifufu/WebNowPlaying-Redux), development will continue over there and while it's a separate listing on the webstore for now it should eventually replace the existing listing.
