### ISSUE TITLE
Twitch support needs updated for new layout

### ISSUE THREAD

**Issue by Gamerbiomek2** [tjhrulz/WebNowPlaying-BrowserExtension#78]
Twitch recently broke the info for your extension :(
every other website works as I tested it and it's a twitch info problem

**Comment by Gamerbiomek2** [comment]
I opened the  log in rainmeter and found a web side error for Twitch
![Web Side error for Twitch](https://user-images.githubusercontent.com/22333494/123588748-3cdbf580-d7b6-11eb-9b83-803061f70a1c.png)

**Comment by keifufu** [comment]
Fixed [here](https://github.com/keifufu/WebNowPlaying-Redux), development will continue over there and while it's a separate listing on the webstore for now it should eventually replace the existing listing.
