### ISSUE TITLE
Webplayer request: Paradise Radio and 101.ru

### ISSUE THREAD

**Issue by 1ucay** [tjhrulz/WebNowPlaying-BrowserExtension#80]
Hi, thank you for your work, it is awesome. 
If you have some free time :D, can you please add support for
https://radioparadise.com or
101.ru - for example New York is nice for listening -> https://101.ru/radio/channel/64

Thank you.

**Comment by keifufu** [comment]
If this is still in demand, please open a Issue [here](https://github.com/keifufu/WebNowPlaying-Redux)
