### ISSUE TITLE
Found Out A Simple Way to Support Many Websites

### ISSUE THREAD

**Issue by MostOriginalIGN** [tjhrulz/WebNowPlaying-BrowserExtension#82]
Hi! I was using WebNowPlaying but I realized that it wasn't working for some sites. So, as a developer, I looked for better ways to get the now playing status. Which is when I remembered Chrome has a built in media controller that shows the song name, artist, and cover art.
<img width="299" alt="Global Media Controls" src="https://user-images.githubusercontent.com/78519393/149461004-8f811664-7ff2-4854-9f79-c32525775ec2.png">
So I looked on how I could pull data from that. I found a way that is surprisingly easy!
`navigator.mediaSession`
Tidal
<img width="633" alt="Playing Industry Baby by LilNasX Example" src="https://user-images.githubusercontent.com/78519393/149461230-27656647-fd17-4889-a967-505b58ee00bf.png">
Soundcloud
<img width="626" alt="image" src="https://user-images.githubusercontent.com/78519393/149461837-a92fb042-b8d8-4972-9f45-2f4597c45b5f.png">
Spotify
<img width="556" alt="image" src="https://user-images.githubusercontent.com/78519393/149462094-0e7a25cf-5f2f-4604-91cb-1f903e4611e0.png">

I hope that this can help make this extension better by supporting a lot more media websites.

**Comment by DarkCeptor44** [comment]
Since you're a developer you could at the very least make a PR so that it's easier for the owner of this repo to merge (and maybe see it?).
PS. I'm new here so I don't know how well maintained this is.

**Comment by keifufu** [comment]
This is a decent idea, however a lot of websites don't support it. It's barely supported by big players like spotify even, as you see it never ends up setting the 'playbackState', and it also doesn't provide us with functions to pause/play/set volume, etc.
Future development of the browser extension will continue [here](https://github.com/keifufu/WebNowPlaying-Redux), where mediaSessions are already made use of where ever it made sense.
