### ISSUE TITLE
Qobuz issue with duration

### ISSUE THREAD

**Issue by J-Louis** [tjhrulz/WebNowPlaying-BrowserExtension#83]
Retrieve "_[object HTMLSpanElement]_" within duration field.
Could be in : 	
qobuzInfoHandler.positionString = function()
	{
		return document.getElementsByClassName("player__track-time-content")[0].children[0];
	};
Miss an _.innerText_ ?

**Comment by keifufu** [comment]
Refer to [this comment](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/85#issuecomment-1439819605)
