### ISSUE TITLE
Qobuz issue with play/pause state

### ISSUE THREAD

**Issue by J-Louis** [tjhrulz/WebNowPlaying-BrowserExtension#84]
The play/pause state seems to be inverted.
Perhaps in :
	qobuzInfoHandler.state = function()
	{
		return document.getElementsByClassName("player__action")[0].children[2].className.includes("pause") ? 2 : 1;
	};
Should be **1 : 2** ?

**Comment by keifufu** [comment]
Refer to [this comment](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/85#issuecomment-1439819605)
