### ISSUE TITLE
Qobuz issue with Album

### ISSUE THREAD

**Issue by J-Louis** [tjhrulz/WebNowPlaying-BrowserExtension#85]
The album field contains the artist value.
Probably in : 
	qobuzInfoHandler.album = function()
	{
		return document.getElementsByClassName("player__track-album")[0].children[0].innerText;
	};
need to use children[2] ?
example : 
```
<div class="player__track-album">
  <a href="/artist/12623">Francis Lai</a>
  <span>&nbsp;-&nbsp;</span>
  <a href="/album/sit6ngu9cnwoc">Les Uns et les Autres (Bande originale du film) (40ème anniversaire)</a>
</div>
```

**Comment by keifufu** [comment]
This repo won't see further development, please open an issue [here](https://github.com/keifufu/WebNowPlaying-Redux) if you'd still like to see Qobuz support.
