### ISSUE TITLE
Manifest version 2 is getting depracated

### ISSUE THREAD

**Issue by Drgabi18** [tjhrulz/WebNowPlaying-BrowserExtension#87]
As the [titles says](https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/87)
As the [warning suggests](https://developer.chrome.com/docs/extensions/mv2/manifestVersion/)
As the [errors show](https://cdn.discordapp.com/attachments/148718731743199233/953640231440093245/unknown.png)
(And maybe the reason why it isn't on the Chrome store anymore, however the [blog post](https://developer.chrome.com/blog/mv2-transition/) doesn't support that)

Just a heads-up notice

**Comment by keifufu** [comment]
Future development of the browser extension will continue [here](https://github.com/keifufu/WebNowPlaying-Redux). It is a separate listing on the chrome webstore / mozilla addon store for now but it should replace the original soon enough.
