### ISSUE TITLE
Add support for youtube.com/tv

### ISSUE THREAD

**Issue by ghost** [tjhrulz/WebNowPlaying-BrowserExtension#9]
So it doesnt work with Chrome incognito tab even if i enable the extension in incognito mode. 
Can you please fix there ?
Im trying it with youtube and it doesnt work in incognito tab.

EDIT: It doesnt work with youtube.com/tv if u know what i mean.

**Comment by tjhrulz** [comment]
Odd, I'll into it when I get home today. There may be a layout difference when browsing YouTube when incognito

**Comment by ghost** [comment]
Okay Thank You :)

**Comment by ghost** [comment]
EDIT: It doesnt work with youtube.com/tv if u know what i mean.

**Comment by tjhrulz** [comment]
Oh, YouTube tv is a different thing I never added support for. I'll add it to the list

**Comment by ghost** [comment]
Cool Thank You
