### ISSUE TITLE
Bandcamp isn't picked up

### ISSUE THREAD

**Issue by Pocket2441** [tjhrulz/WebNowPlaying-BrowserExtension#90]
@tjhrulz

![image](https://user-images.githubusercontent.com/81384675/185462894-f85c41a2-63d3-4b6c-88f8-1921c54de32d.png)

![image](https://user-images.githubusercontent.com/81384675/185463319-2a6c94b0-3a39-428a-bbe8-14ea057bc29a.png)

And web now playing is selected
![image](https://user-images.githubusercontent.com/81384675/185462967-0c34b7c8-2de0-485a-b606-4ebd5a0f2850.png)

![image](https://user-images.githubusercontent.com/81384675/185463319-2a6c94b0-3a39-428a-bbe8-14ea057bc29a.png)

skin is cleartext

**Comment by korben-open** [comment]
![image](https://user-images.githubusercontent.com/81384675/185462736-3aade3ec-6bb7-4ff4-828f-14bba6cc0d4e.png)
more claer image

**Comment by keifufu** [comment]
Bandcamp support was added in the new version, which you can find [here](https://github.com/keifufu/WebNowPlaying-Redux). It is a separate listing on the chrome webstore / mozilla addon store for now but it should replace the original soon enough.
