### ISSUE TITLE
WebNowPlaying not working with Brave browser

### ISSUE THREAD

**Issue by ghost** [tjhrulz/WebNowPlaying-BrowserExtension#92]
It doesn't show up when I play any media in Brave but it worked if I use other browser like Chrome
![Screenshot_7](https://user-images.githubusercontent.com/114146835/201504419-0d7f1199-d906-400a-8128-998921195564.png)

**Comment by racked23** [comment]
One temporary fix I've found was to disable Shields on Youtube. Still trying to find a whitelist so I can add this to it, as it seems that UBlock and other Adblock extension need this to make WNP work.

music.amazon.com 127.0.0.1 * allow
play.google.com 127.0.0.1 * allow
soundcloud.com 127.0.0.1 * allow
tidal.com 127.0.0.1 * allow
www.pandora.com 127.0.0.1 * allow
www.spotify.com 127.0.0.1 * allow
www.twitch.tv 127.0.0.1 * allow
www.youtube.com 127.0.0.1 * allow

**Comment by racked23** [comment]
![image](https://user-images.githubusercontent.com/78748733/205890346-feb073da-9fa5-4b80-b58f-36f066445f32.png)

Found the culprit, need to whitelist it somehow

**Comment by racked23** [comment]
Found it, @OliveLikesBlue , you need to go into brave://adblock, custom filters section, and add this line

@@ws://127.0.0.1:8974

then save changes and restart the browser.

**Comment by ghost** [comment]
omg thanks for helping it worked :)
