### ISSUE TITLE
Chrome plugin not working on Opera(GX) (Randomly fixed)

### ISSUE THREAD

**Issue by Anoulom1** [tjhrulz/WebNowPlaying-BrowserExtension#96]
Since opera is made with chromium, you're able to download chrome plugins, it seems like the plugin doesn't work on Opera atm. I only tested this on OperaGX so normal Opera might work.

**Comment by Anoulom1** [comment]
Seems like it is fixed, don't know what hapenned but it works now

**Comment by keifufu** [comment]
Closing this as it seems to work again for you.
